version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
      - video-data:/app/data/videos
      - db-data:/app/data/db
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: always
    networks:
      - app-network-videocourses
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    restart: always
    networks:
      - app-network-videocourses

networks:
  app-network-videocourses:
    driver: bridge

volumes:
  video-data:
  db-data: