version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: video-platform-client
    restart: always
    ports:
      - "8080:80"  # Изменено с 80:80 на 8080:80 для избежания конфликта
    depends_on:
      - server
    networks:
      - app-network-videocourses
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: video-platform-server
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"  # Changed from 4001:5000 to 5000:5000 for production
    volumes:
      - video-data:/app/data/videos
      - db-data:/app/data/db
    networks:
      - app-network-videocourses
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  app-network-videocourses:
    driver: bridge

volumes:
  video-data:
    driver: local
  db-data:
    driver: local